// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48_VGtG2ZMnupFkMkzgMLgHDgSNspRto',
    appId: '1:74858547630:web:74b56ae2a2d244bcff203f',
    messagingSenderId: '74858547630',
    projectId: 'mi-proyecto1-52250',
    authDomain: 'mi-proyecto1-52250.firebaseapp.com',
    databaseURL: 'https://mi-proyecto1-52250-default-rtdb.firebaseio.com',
    storageBucket: 'mi-proyecto1-52250.firebasestorage.app',
    measurementId: 'G-GM52S5VD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bZuKAF-56bY9EJRAFJaYSG-wCU_X9Xw',
    appId: '1:74858547630:android:910c55ed1cee4238ff203f',
    messagingSenderId: '74858547630',
    projectId: 'mi-proyecto1-52250',
    databaseURL: 'https://mi-proyecto1-52250-default-rtdb.firebaseio.com',
    storageBucket: 'mi-proyecto1-52250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q3BhU-ndRwzry9CqWZLp-w_n_hxAcgY',
    appId: '1:74858547630:ios:2de8763fb01353e2ff203f',
    messagingSenderId: '74858547630',
    projectId: 'mi-proyecto1-52250',
    databaseURL: 'https://mi-proyecto1-52250-default-rtdb.firebaseio.com',
    storageBucket: 'mi-proyecto1-52250.firebasestorage.app',
    iosBundleId: 'com.example.zfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Q3BhU-ndRwzry9CqWZLp-w_n_hxAcgY',
    appId: '1:74858547630:ios:2de8763fb01353e2ff203f',
    messagingSenderId: '74858547630',
    projectId: 'mi-proyecto1-52250',
    databaseURL: 'https://mi-proyecto1-52250-default-rtdb.firebaseio.com',
    storageBucket: 'mi-proyecto1-52250.firebasestorage.app',
    iosBundleId: 'com.example.zfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB48_VGtG2ZMnupFkMkzgMLgHDgSNspRto',
    appId: '1:74858547630:web:52460d5ed4dc75f7ff203f',
    messagingSenderId: '74858547630',
    projectId: 'mi-proyecto1-52250',
    authDomain: 'mi-proyecto1-52250.firebaseapp.com',
    databaseURL: 'https://mi-proyecto1-52250-default-rtdb.firebaseio.com',
    storageBucket: 'mi-proyecto1-52250.firebasestorage.app',
    measurementId: 'G-RE3S26BW04',
  );

}